name: Keep Streamlit Awake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit app
        run: |
          curl --fail --max-time 60 \
          -A "Mozilla/5.0" \
          "https://financial-agent-zc-v1.streamlit.app//"
